### ISSUE TITLE
Lockscreen is freezing right when pattern ends

### ISSUE THREAD

**Issue by emerali** [AlstonLin/TheLearningLock#39]
Only seems to be happening to me, so i'll try to figure out where things are breaking.

I suspect that it might have something to do with the training process; either it's gotten too large to process easily or some calculation error is screwing things up.

**Comment by emerali** [comment]
Possibly related to #41

**Comment by AlstonLin** [comment]
A fix for #41 should if been already pushed. Do you still have this problem?

**Comment by emerali** [comment]
seems to be working now
